### ISSUE TITLE
dart_jts build issues with flutter 3.0

### ISSUE THREAD

**Issue by iulian0512** [moovida/dart_jts#12]
Because dart_jts 0.2.1 depends on collection >=1.14.13 <=1.15.0 and no versions of dart_jts match >0.2.1 <0.3.0, dart_jts ^0.2.1 requires collection >=1.14.13 <=1.15.0.
And because every version of flutter_test from sdk depends on collection 1.16.0, dart_jts ^0.2.1 is incompatible with flutter_test from sdk.

**Comment by moovida** [comment]
Hi there, yes, I am currently abroad, but this needs to be a migration for all the SMASH upstream projects, so it will need some time to do it all together.
I will look into it soon though.

**Comment by sanak** [comment]
@moovida Okay, thanks for the confirmation!

**Comment by sanak** [comment]
@moovida
Thanks! I confirmed that `flutter pub get` and `flutter test` on the latest `master` branch works without the error.

**Comment by iulian0512** [comment]
@moovida  thanks for the fix
