### ISSUE TITLE
Dependency error with flutter 3.7 and the collection package.

### ISSUE THREAD

**Issue by jetpeter** [moovida/dart_jts#16]
Flutter 3.7 released to stable requires collection 1.17. 

`Because every version of flutter_test from sdk depends on collection 1.17.0 and dart_jts >=0.2.1+1 depends on collection >=1.14.13 <=1.16.0, flutter_test from sdk is incompatible with dart_jts >=0.2.1+1.`

https://github.com/moovida/dart_jts/blob/7dd6eba127e20f6a1ba88b38e8434cf4920d4937/pubspec.yaml#L13

**Comment by iulian0512** [comment]
also have the issue, why is this constraint used ?

**Comment by moovida** [comment]
this should be fixed now, cleaned up deps

**Comment by iulian0512** [comment]
@moovida please see https://github.com/moovida/dart_jts/pull/17
