### ISSUE TITLE
Problem reading GeometryCollection

### ISSUE THREAD

**Issue by bettdouglas** [moovida/dart_jts#2]
`
const String WKT_GC =
    'GEOMETRYCOLLECTION (POLYGON ((100 200, 200 200, 200 100, 100 100, 100 200)), LINESTRING (150 250, 250 250))';
`
Reading the geometry above using rdr below fails with 

> Invalid argument(s): Operation does not support GeometryCollection arguments
package:dart_jts/src/com/hydrologis/dart_jts/geom/geometry.dart 1687:7  Geometry.checkNotGeometryCollection
package:dart_jts/src/com/hydrologis/dart_jts/geom/geometry.dart 913:5   Geometry.relate
package:dart_jts/src/com/hydrologis/dart_jts/geom/geometry.dart 967:12  Geometry.equalsTopo
package:dart_jts/src/com/hydrologis/dart_jts/geom/geometry.dart 937:12  Geometry.equals
test\geometry_test.dart 183:25                                          main.<fn>.<fn>

`final geomFactory = GeometryFactory.withCoordinateSequenceFactory(PackedCoordinateSequenceFactory.withType(PackedCoordinateSequenceFactory.DOUBLE));
`
`final rdr = WKTReader.withFactory(geomFactory);`
`final actualGeom = rdr.read(WKT_GC);
`

**Comment by moovida** [comment]
Hi @bettdouglas , the wktreader is the only part not directly migrated from Java due to some missing tokenizer classes.

But I tried to setup a testcase with your example and it works:

```
    test("testGeometryCollection", () {
      // act
      const String WKT_GC =
          'GEOMETRYCOLLECTION (POLYGON ((100 200, 200 200, 200 100, 100 100, 100 200)), LINESTRING (150 250, 250 250))';

      final geomFactory = GeometryFactory.withCoordinateSequenceFactory(
          PackedCoordinateSequenceFactory.withType(
              PackedCoordinateSequenceFactory.DOUBLE));
      final rdr = WKTReader.withFactory(geomFactory);
      final actualGeom = rdr.read(WKT_GC);
      print(actualGeom);
    });
```

the print throws out:
```
GEOMETRYCOLLECTION (POLYGON ((100 200, 200 200, 200 100, 100 100, 100 200)), LINESTRING (150 250, 250 250))
✓ WKTReaderTest -  testGeometryCollection
Exited
```

Not sure when you get the issue.

**Comment by bettdouglas** [comment]
Okay, sorry I didn't frame it well. One of my tests was failing but i realized the error was  because of trying to compare two GeometryCollections.

**Comment by bettdouglas** [comment]
```
  test('GeometryCollection Equality', () {

    final WKT_GC =
    'GEOMETRYCOLLECTION (POLYGON ((100 200, 200 200, 200 100, 100 100, 100 200)), LINESTRING (150 250, 250 250))';

    final geometryCollection = rdr.read(WKT_GC);
    final geometryCollection2 = rdr.read(WKT_GC);

    expect(geometryCollection.equals(geometryCollection2), true);

  });
```

This fails with an issue. Sorry for not following up soon.

**Comment by moovida** [comment]
This is actually not an error, looking at the original JTS code.

The equals makes also a topological equality check (it is wired to the equalsTopo method), which is not supported for collections.

You probably want to check this method: equalsExactGeom
