### ISSUE TITLE
polygon intersection?

### ISSUE THREAD

**Issue by Duanyinyin504** [moovida/dart_jts#20]
Thank you for providing this library. I need to calculate the intersection length of polylines and polygons, but it shows "Not implemented yet". How can I implement it? I am looking forward to your reply.

**Comment by moovida** [comment]
Hi @Duanyinyin504 , that sounds strange to me. I use geometry intersections all the time. I think only GeometryCollections are not supported yet. Can you show me your usecase with an example?

**Comment by Duanyinyin504** [comment]
Thanks for your reply, here is my example
![DO2BYF7KZ~9F8FE S3BW}TL](https://github.com/moovida/dart_jts/assets/15697958/561a7bb9-5f93-4837-b873-f5c88d63bdf6)

**Comment by moovida** [comment]
Hi @Duanyinyin504 , I just checked and confirm that intersection is not implemented yet. That is quite a pity, I thought it was. To implement intersection you will have to port the related portions from the JTS java project to this one. 

Here is the code: https://github.com/locationtech/jts/

You will have to find the Geometry class and migrate the java code to here: https://github.com/moovida/dart_jts/blob/master/lib/src/com/hydrologis/dart_jts/geom/geometry.dart#L1201

**Comment by Duanyinyin504** [comment]
@moovida，Yes, thank you for pointing it out. Now my project is too busy and I can't port this project for the time being. It's a shame.
