### ISSUE TITLE
How to check if a polygon edge crosses another edge within the same polygon

### ISSUE THREAD

**Issue by iwishiwasaneagle** [moovida/dart_jts#4]
Hi, 

In my code I am trying to check whether a polygon is "valid" or not. A valid polygon in my case is one where none of the edges within the geometry intersect. For example:
 

- Valid: [(0,0),(0,1),(1,1),(1,0)]

 

- Invalid: [[(0,0),(0,1),(0.5,-1),(1,1),(1,0)]]

How would I do this? So far `crosses` and `intersect` don't work for a whole polygon. Would I have to iterate over each edge? 

Many thanks in advance!

**Comment by moovida** [comment]
Sorry, I Am from mobile, so I am not able to check. Isn't there an isValid that checks self intersection?

**Comment by iwishiwasaneagle** [comment]
> Sorry, I Am from mobile, so I am not able to check. Isn't there an isValid that checks self intersection?

I figured it out using `LineString`s. However, I'm sure your method would work too. I wasn't aware that `isValid` does a similar thing for polygons.

```
bool polygonsCrossSelf(List<Offset> poly) {
  if(poly.length<3) return false;

  List<Offset> polyCopy = List.from(poly);

  /// Close the polygon, if not already done
  if(polyCopy.first != polyCopy.elementAt(polyCopy.length-1)){
    polyCopy.add(polyCopy.first);
  }

  /// Convert the [List<Offset>] into [List<Coordinate>]
  List<Coordinate> polyCoords =
  polyCopy.map((e) => Coordinate(e.dx, e.dy)).toList();

  return  !LineString.fromSequence(CoordinateArraySequence(polyCoords), GeometryFactory.defaultPrecision()).isSimple();
}
```
