### ISSUE TITLE
polygon union ?

### ISSUE THREAD

**Issue by mohammedX6** [moovida/dart_jts#7]
Thanks for the library.
How I can do polygon union using this library?

**Comment by moovida** [comment]
I am afraid that is one of the operations that has not been ported yet. 
It would be great if someone could contribute it as PR.

**Comment by killerm250m** [comment]
I managed to port this awesome library https://github.com/velipso/polybooljs but without tests if you want to do the test by yourself tell me so I can give you the source code.

**Comment by moovida** [comment]
Hi @killerm250m , this library ports only from the https://github.com/locationtech/jts library, which has a test for every tiny usecase. So thanks for the proposal, but no thanks. I would have hoped that you would port the JTS part. Without testcases there is just too much work and uncertainty behind such complex geometry operations.

**Comment by killerm250m** [comment]
I will try in the future.
On the other hand, can you tell me the functions that are not imported yet?

**Comment by moovida** [comment]
It is not very simple to make a list, They are really a lot. Best bet would be to check the testcases. There are many for every supported functionality.

If you have doubts, just ask here, I will give you some information about the functionality and if it is missing I will gladly link you to the exact position of that code in the JTS project for a simpler port.
