### ISSUE TITLE
create buffer for line string 

### ISSUE THREAD

**Issue by mohammedX6** [moovida/dart_jts#9]
I am trying to create a buffer for a LINESTRING 

LINESTRING (35.8027978006563146 31.8588533106116252, 35.8105578052783642 31.8586604663966249, 35.8105417762212284 31.8520311786293853, 35.8027978006563146 31.8588533106116252)

![Screen Shot 2021-11-04 at 12 51 53 PM](https://user-images.githubusercontent.com/24648104/140301688-9f7a823f-f92c-4738-a8e6-c7500cf922d0.png)

What i do:
JTS.BufferParameters bufParams =  JTS. BufferParameters();
JTS.Polygon bufferd=JTS.BufferOp.bufferOpWithParams(geometry, .000001, bufParams);

but the buffer result is wrong 
POLYGON ((35.8027978006563146 31.8588533106116252, 35.8027978254996881 31.8588543103029807, 35.8105578301217378 31.8586614660879803, 35.8105580219384336 31.8586614426437329, 35.8105582056643286 31.8586613827432181, 35.8105583744385001 31.8586612886233205, 35.8105585219583702 31.8586611637987822, 35.8105586427150584 31.8586610129309626, 35.8105587321991194 31.8586608416537587, 35.8105587870689206 31.8586606563632238, 35.8105588052754413 31.8586604639787154, 35.8105427762183055 31.8520311762114758, 35.8105427575970623 31.8520309865318154, 35.810542703327215 31.8520308038301252, 35.8105426153801361 31.8520306347430626, 35.8105424969504966 31.8520304854127403, 35.8105423523402848 31.8520303612635942, 35.810542186802472 31.8520302668053645, 35.8105420063502464 31.8520302054692586, 35.8105418175385566 31.8520301794833109, 35.8105416272260086 31.8520301897914706, 35.8105414423257287 31.8520302360192886, 35.8105412695542498 31.8520303164875358, 35.8105411151875046 31.8520304282731921, 35.8027971396225908 31.85885256

![Screen Shot 2021-11-04 at 12 53 37 PM](https://user-images.githubusercontent.com/24648104/140301839-e57fe0dd-fcda-49a8-9e86-e514e8c3e68a.png)

I want the buffer like this way:

![single-sided-buffer-right](https://user-images.githubusercontent.com/24648104/140301953-5e592869-7bd5-42eb-8b36-63d33e034b8f.png)

**Comment by moovida** [comment]
If you create a pull request with a testcase in which this happens, I will look at it. I can't think that the buffer function is failing on such a simple usecase.

For the record, what you are looking for is a singlesided buffer, which 'should' be supported. 

But sure the first step is to check if the error you show is real.

**Comment by mohammedX6** [comment]
@moovida never mind after hours of searching for the problem I find that I have some wrong corrdiantes.
